FROM openjdk:14-jdk-alpine3.10
LABEL description="image to contain a springboot microservice app"
RUN mkdir -p /usr/src/app && chmod 755 /usr/src/app
WORKDIR /usr/src/app
CMD /opt/openjdk-14/bin/java -jar ${JARNAME}
